disabled_rules:
    - unused_optional_binding
    - unused_setter_value
type_name:
    excluded:
        - T
line_length:
    warning: 160
    ignores_comments: true
function_body_length: 50
identifier_name:
    excluded:
        - id
included:
    - ios
    - plugins
