name: PlayerUI
packages:
  PlayerUI:
    path: .
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector
    exactVersion: "0.9.8"
configs:
  AdHoc: debug
  Debug: debug
  Release: release
options:
  # prevents BUNDLE_LOADER from being added to test target
  # which was preventing code coverage for unit tests
  settingPresets: project
targets:
  PlayerUIDemo:
    type: application
    sources: ./xcode/demo
    platform: iOS
    deploymentTarget: "14.0"
    settings:
      base:
        # https://github.com/yonaskolb/XcodeGen/blob/3757f82bf6ed3916235828a3e3d64fa0c787d564/SettingPresets/Product_Platform/application_iOS.yml
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_IDENTITY: iPhone Developer

        # https://github.com/yonaskolb/XcodeGen/blob/3757f82bf6ed3916235828a3e3d64fa0c787d564/SettingPresets/Platforms/iOS.yml
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/Frameworks"]
        SDKROOT: iphoneos
        TARGETED_DEVICE_FAMILY: '1,2'

        DEVELOPMENT_TEAM: F6DWWXWEX6
        PRODUCT_BUNDLE_IDENTIFIER: com.intuit.ios.player
      configs:
        adhoc:
          CODE_SIGN_STYLE: Automatic
        debug:
          CODE_SIGN_STYLE: Manual
          PROVISIONING_PROFILE_SPECIFIER: "match InHouse com.intuit.ios.player"
          CODE_SIGN_IDENTITY: "iPhone Distribution"
        release:
          CODE_SIGN_STYLE: Manual
          PROVISIONING_PROFILE_SPECIFIER: "match InHouse com.intuit.ios.player"
          CODE_SIGN_IDENTITY: "iPhone Distribution"
    dependencies:
      - package: PlayerUI
        product: PlayerUI
      - package: PlayerUI
        product: PlayerUIReferenceAssets
      - package: PlayerUI
        product: PlayerUIBeaconPlugin
      - package: PlayerUI
        product: PlayerUICommonExpressionsPlugin
      - package: PlayerUI
        product: PlayerUICommonTypesPlugin
      - package: PlayerUI
        product: PlayerUIExpressionPlugin
      - package: PlayerUI
        product: PlayerUIExternalActionPlugin
      - package: PlayerUI
        product: PlayerUIExternalActionViewModifierPlugin
      - package: PlayerUI
        product: PlayerUIMetricsPlugin
      - package: PlayerUI
        product: PlayerUIPubSubPlugin
      - package: PlayerUI
        product: PlayerUIPrintLoggerPlugin
      - package: PlayerUI
        product: PlayerUISwiftUICheckPathPlugin
      - package: PlayerUI
        product: PlayerUISwiftUIPendingTransactionPlugin
      - package: PlayerUI
        product: PlayerUITransitionPlugin
      - package: PlayerUI
        product: PlayerUITypesProviderPlugin
      - package: PlayerUI
        product: PlayerUITestUtilities
  Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: ./ios/Tests
      - path: ./ios/TestUtilities
    info:
      path: ./ios/Tests/Info.plist
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/PlayerUIDemo.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PlayerUIDemo
      TEST_TARGET_NAME: PlayerUIDemo
      SDKROOT: iphoneos
      TARGETED_DEVICE_FAMILY: '1,2'
      # default from settingPreset https://github.com/yonaskolb/XcodeGen/blob/3757f82bf6ed3916235828a3e3d64fa0c787d564/SettingPresets/Products/bundle.unit-test.yml
      LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@loader_path/Frameworks"]
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: F6DWWXWEX6
      PRODUCT_BUNDLE_IDENTIFIER: com.intuit.ios.player
      CODE_SIGN_IDENTITY: "iPhone Distribution"
    dependencies:
      - target: PlayerUIDemo
      - package: PlayerUI
        product: PlayerUI
      - package: PlayerUI
        product: PlayerUILogger
      - package: PlayerUI
        product: PlayerUIBaseBeaconPlugin
      - package: PlayerUI
        product: PlayerUICheckPathPlugin
      - package: PlayerUI
        product: PlayerUIComputedPropertiesPlugin
      - package: PlayerUI
        product: PlayerUICommonExpressionsPlugin
      - package: PlayerUI
        product: PlayerUICommonTypesPlugin
      - package: PlayerUI
        product: PlayerUIExternalActionPlugin
      - package: PlayerUI
        product: PlayerUIExpressionPlugin
      - package: PlayerUI
        product: PlayerUIMetricsPlugin
      - package: PlayerUI
        product: PlayerUIPubSubPlugin
      - package: PlayerUI
        product: PlayerUIPrintLoggerPlugin
      - package: PlayerUI
        product: PlayerUIStageRevertDataPlugin
      - package: PlayerUI
        product: PlayerUITypesProviderPlugin
      - package: PlayerUI
        product: PlayerUIReferenceAssets
      - package: PlayerUI
        product: PlayerUITestUtilitiesCore

  ViewInspectorTests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: ./ios/ViewInspector
      - path: ./ios/TestUtilities
    info:
      path: ./ios/ViewInspector/Info.plist
    settings:
      # defaults from settingPreset https://github.com/yonaskolb/XcodeGen/blob/3757f82bf6ed3916235828a3e3d64fa0c787d564/SettingPresets/Products/bundle.ui-testing.yml
      BUNDLE_LOADER: $(TEST_HOST)
      LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@loader_path/Frameworks"]
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: F6DWWXWEX6
      PRODUCT_BUNDLE_IDENTIFIER: com.intuit.ios.PlayerUI-ExampleUITests
      PROVISIONING_PROFILE_SPECIFIER: "match Development com.intuit.ios.PlayerUI-ExampleUITests*"
      CODE_SIGN_IDENTITY: "iPhone Distribution"
    dependencies:
      - package: ViewInspector
      - target: PlayerUIDemo
      - package: PlayerUI
        product: PlayerUI
      - package: PlayerUI
        product: PlayerUIBaseBeaconPlugin
      - package: PlayerUI
        product: PlayerUIBeaconPlugin
      - package: PlayerUI
        product: PlayerUISwiftUICheckPathPlugin
      - package: PlayerUI
        product: PlayerUISwiftUIPendingTransactionPlugin
      - package: PlayerUI
        product: PlayerUIMetricsPlugin
      - package: PlayerUI
        product: PlayerUIExternalActionViewModifierPlugin
      - package: PlayerUI
        product: PlayerUITransitionPlugin
      - package: PlayerUI
        product: PlayerUIReferenceAssets
      - package: PlayerUI
        product: PlayerUITestUtilitiesCore